sudo: false
language: generic

services:
  - docker

before_script:
  - rm -Rf ./build/ ./jvmw.properties ~/.jvm/

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis_retry sudo apt-get update && travis_retry sudo apt-get install -y curl; fi
  - if [[ ! -z "$DOCKER_IMAGE" ]]; then sudo docker pull $DOCKER_IMAGE:$DOCKER_TAG; fi

script:
  - if [[ -z "$DOCKER_IMAGE" ]]; then ./test_suite.sh 2>&1; fi
  - if [[ ! -z "$DOCKER_IMAGE" and  ]] && [[ "$DOCKER_IMAGE" -eq "ubuntu" -o "$DOCKER_IMAGE" -eq "debian" ]]; then docker run --rm -v "`pwd`/jdkw":/root/jdkw -v "`pwd`/test/":/root/test/ -v "`pwd`/samples/":/root/samples/ -v "`pwd`/test_suite.sh":/root/test_suite.sh -v "`pwd`/tests.sh":/root/tests.sh -v "`pwd`/tmp.volume":/root/.jvm -it --rm $DOCKER_IMAGE:$DOCKER_TAG bash -c "sudo apt-get update && sudo apt-get install -y curl && cd /root && ./test_suite.sh 2>&1"; fi
  - if [[ ! -z "$DOCKER_IMAGE" and  ]] && [[ "$DOCKER_IMAGE" -eq "centos" ]]; then docker run --rm -v "`pwd`/jdkw":/root/jdkw -v "`pwd`/test/":/root/test/ -v "`pwd`/samples/":/root/samples/ -v "`pwd`/test_suite.sh":/root/test_suite.sh -v "`pwd`/tests.sh":/root/tests.sh -v "`pwd`/tmp.volume":/root/.jvm -it --rm $DOCKER_IMAGE:$DOCKER_TAG bash -c "cd /root && ./test_suite.sh 2>&1"; fi

matrix:
  fast_finish: true
  include:
    - os: osx
      before_install:
        - travis_retry brew update
        - travis_retry brew install shellcheck
      script:
        - find . \( -name 'jdkw' -o -name '*.sh' \) -exec shellcheck {} \;
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.3

    - os: linux
    - os: linux
      dist: trusty
    - os: linux
      dist: precise
    - os: linux
      sudo: required
      env:
        - DOCKER_IMAGE: centos
        - DOCKER_TAG: centos6
    - os: linux
      sudo: required
      env:
        - DOCKER_IMAGE: centos
        - DOCKER_TAG: centos7
    - os: linux
      sudo: required
      env:
        - DOCKER_IMAGE: debian
        - DOCKER_TAG: wheezy
    - os: linux
      sudo: required
      env:
        - DOCKER_IMAGE: debian
        - DOCKER_TAG: jessie
    - os: linux
      sudo: required
      env:
        - DOCKER_IMAGE: ubuntu
        - DOCKER_TAG: trusty

  allow_failures:
    - os: osx
      osx_image: xcode6.4
