sudo: false
language: generic

services:
  - docker

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$SKIP_SHELLCHECK" != "yes" ]] ; then travis_retry brew update && travis_retry brew install shellcheck; fi
  - chmod +x ./travis_scripts/*.sh

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$SKIP_SHELLCHECK" != "yes" ]] ; then find . \( -name 'jdkw' -o -name '*.sh' \) -exec shellcheck {} \; ; fi
  - if [[ ! -z "$DOCKER_IMAGE" ]]; then sudo docker pull $DOCKER_IMAGE:$DOCKER_TAG; fi

script:
  - if [[ -z "$DOCKER_IMAGE" ]]; then ./test_suite.sh 2>&1; fi

matrix:
  include:
    - os: osx
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode6.4
      env:
        - SKIP_SHELLCHECK=yes

    - os: linux
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: precise
      sudo: required

    - os: linux
      sudo: required
      env:
        - DOCKER_IMAGE: centos
        - DOCKER_TAG: centos6
      script:
        - ./travis_scripts/script_docker.centos.sh
    - os: linux
      sudo: required
      env:
        - DOCKER_IMAGE: centos
        - DOCKER_TAG: centos7
      env:
        - DOCKER_IMAGE: centos
        - DOCKER_TAG: centos6
      script:
        - ./travis_scripts/script_docker.centos.sh
    - os: linux
      sudo: required
      env:
        - DOCKER_IMAGE: debian
        - DOCKER_TAG: wheezy
      script:
        - ./travis_scripts/script_docker.debian.sh
    - os: linux
      sudo: required
      env:
        - DOCKER_IMAGE: debian
        - DOCKER_TAG: jessie
      script:
        - ./travis_scripts/script_docker.debian.sh
    - os: linux
      sudo: required
      env:
        - DOCKER_IMAGE: ubuntu
        - DOCKER_TAG: trusty
      script:
        - ./travis_scripts/script_docker.ubuntu.sh
