sudo: required
language: generic

services:
  - docker

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker --version; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew reinstall shellcheck && brew cask reinstall java; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update && sudo apt-get install -y shellcheck oracle-java9-installer oracle-java9-set-default; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then for DOCKER_IMAGE in ${DOCKER_IMAGES}; do docker pull "${DOCKER_IMAGE}"; done; fi

before_script:
  - find . \( -name 'jdkw' -o -name '*.sh' \) -exec shellcheck -e SC1090 -x {} \;

script:
  - env
  - ./src/test/bash/_test_suite.sh
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./src/test/bash/_test_docker_suite.sh; fi

env:
  global:
    - DOCKER_IMAGES="centos:centos6 centos:centos7 debian:wheezy debian:jessie ubuntu:trusty opensuse:latest base/arch:latest"
  matrix:
# JVM
    - TEST_TYPE=jvm TEST_JVM_TYPE=jdk TEST_JVM_VERSION=9       TEST_FULL_VERSION=9.0.4+11        TEST_REUSE_JAVA_VERSION=9.0.4  TEST_USE_SYSTEM=Y
    - TEST_TYPE=jvm TEST_JVM_TYPE=jdk TEST_JVM_VERSION=9.0.4   TEST_FULL_VERSION=9.0.4+11                                       TEST_USE_SYSTEM=Y
    - TEST_TYPE=jvm TEST_JVM_TYPE=jdk TEST_JVM_VERSION=9.0.1   TEST_FULL_VERSION=9.0.1+11
    - TEST_TYPE=jvm TEST_JVM_TYPE=jdk TEST_JVM_VERSION=8       TEST_FULL_VERSION=1.8.0_161-b12   TEST_REUSE_JAVA_VERSION=8u161
    - TEST_TYPE=jvm TEST_JVM_TYPE=jdk TEST_JVM_VERSION=8u161   TEST_FULL_VERSION=1.8.0_161-b12
    - TEST_TYPE=jvm TEST_JVM_TYPE=jdk TEST_JVM_VERSION=8u162   TEST_FULL_VERSION=1.8.0_162-b12
    - TEST_TYPE=jvm TEST_JVM_TYPE=jdk TEST_JVM_VERSION=8u144   TEST_FULL_VERSION=1.8.0_144-b01
#    - TEST_TYPE=jvm TEST_JVM_TYPE=jdk TEST_JVM_VERSION=7       TEST_FULL_VERSION=1.7.0_80-b15    TEST_REUSE_JAVA_VERSION=7u80
    - TEST_TYPE=jvm TEST_JVM_TYPE=jdk TEST_JVM_VERSION=7u80    TEST_FULL_VERSION=1.7.0_80-b15
# JDK
    - TEST_TYPE=jdk TEST_JVM_TYPE=jdk TEST_JVM_VERSION=9       TEST_FULL_VERSION=9.0.4+11        TEST_REUSE_JAVA_VERSION=9.0.4  TEST_USE_SYSTEM=Y
    - TEST_TYPE=jdk TEST_JVM_TYPE=jdk TEST_JVM_VERSION=9.0.4   TEST_FULL_VERSION=9.0.4+11                                       TEST_USE_SYSTEM=Y
    - TEST_TYPE=jdk TEST_JVM_TYPE=jdk TEST_JVM_VERSION=9.0.1   TEST_FULL_VERSION=9.0.1+11
    - TEST_TYPE=jdk TEST_JVM_TYPE=jdk TEST_JVM_VERSION=8       TEST_FULL_VERSION=1.8.0_161-b12   TEST_REUSE_JAVA_VERSION=8u161
    - TEST_TYPE=jdk TEST_JVM_TYPE=jdk TEST_JVM_VERSION=8u161   TEST_FULL_VERSION=1.8.0_161-b12
    - TEST_TYPE=jdk TEST_JVM_TYPE=jdk TEST_JVM_VERSION=8u162   TEST_FULL_VERSION=1.8.0_162-b12
    - TEST_TYPE=jdk TEST_JVM_TYPE=jdk TEST_JVM_VERSION=8u144   TEST_FULL_VERSION=1.8.0_144-b01
#    - TEST_TYPE=jdk TEST_JVM_TYPE=jdk TEST_JVM_VERSION=7       TEST_FULL_VERSION=1.7.0_80-b15    TEST_REUSE_JAVA_VERSION=7u80
    - TEST_TYPE=jdk TEST_JVM_TYPE=jdk TEST_JVM_VERSION=7u80    TEST_FULL_VERSION=1.7.0_80-b15

os:
  - osx
  - linux