
sudo: required
language: generic

services:
  - docker

env:
  global:
    - JVM_WRAPPER_VERSION="`date +%Y%m%d_%H%M%S`"


install:
    
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap caskroom/versions; fi
      
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
      
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew reinstall shellcheck bats-core; fi
      
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask uninstall java; fi
      
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew search java; fi
      
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker --version; fi
      
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:duggan/bats; fi
      
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
      
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y shellcheck bats; fi
      
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-cache search oracle-; fi
      
before_script:
  - while IFS='' read -r line || [[ -n "${line}" ]]; do eval "export ${line}"; done < "samples.properties/${ENV_TEST_FILE}.env"
  - env
  - make build_sh || travis_terminate 1

jobs:
  include:

    - stage: test
      env:
        - ENV_TEST_FILE="openjdk-12"
        - DOCKER_IMAGE=""
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="openjdk-8"
        - DOCKER_IMAGE=""
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="oracle-11"
        - DOCKER_IMAGE=""
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="oracle-8"
        - DOCKER_IMAGE=""
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="openjdk-12"
        - DOCKER_IMAGE="centos:centos6"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="openjdk-8"
        - DOCKER_IMAGE="centos:centos6"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="oracle-11"
        - DOCKER_IMAGE="centos:centos6"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="oracle-8"
        - DOCKER_IMAGE="centos:centos6"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="openjdk-12"
        - DOCKER_IMAGE="centos:centos7"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="openjdk-8"
        - DOCKER_IMAGE="centos:centos7"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="oracle-11"
        - DOCKER_IMAGE="centos:centos7"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="oracle-8"
        - DOCKER_IMAGE="centos:centos7"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="openjdk-12"
        - DOCKER_IMAGE="debian:wheezy"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="openjdk-8"
        - DOCKER_IMAGE="debian:wheezy"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="oracle-11"
        - DOCKER_IMAGE="debian:wheezy"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="oracle-8"
        - DOCKER_IMAGE="debian:wheezy"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="openjdk-12"
        - DOCKER_IMAGE="debian:jessie"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="openjdk-8"
        - DOCKER_IMAGE="debian:jessie"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="oracle-11"
        - DOCKER_IMAGE="debian:jessie"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="oracle-8"
        - DOCKER_IMAGE="debian:jessie"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="openjdk-12"
        - DOCKER_IMAGE="ubuntu:trusty"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="openjdk-8"
        - DOCKER_IMAGE="ubuntu:trusty"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="oracle-11"
        - DOCKER_IMAGE="ubuntu:trusty"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="oracle-8"
        - DOCKER_IMAGE="ubuntu:trusty"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="openjdk-12"
        - DOCKER_IMAGE="opensuse:latest"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="openjdk-8"
        - DOCKER_IMAGE="opensuse:latest"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="oracle-11"
        - DOCKER_IMAGE="opensuse:latest"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="oracle-8"
        - DOCKER_IMAGE="opensuse:latest"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="openjdk-12"
        - DOCKER_IMAGE="base/arch:latest"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="openjdk-8"
        - DOCKER_IMAGE="base/arch:latest"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="oracle-11"
        - DOCKER_IMAGE="base/arch:latest"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        
    - stage: test
      env:
        - ENV_TEST_FILE="oracle-8"
        - DOCKER_IMAGE="base/arch:latest"
      script:
        - make check_sh || travis_terminate 1
        - cp ./wrapper-sh/build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1
        