sudo: false
language: generic

services:
  - docker

script:
  - env

env:
  - JVM_VERSION=9 TEST_FULL_VERSION=9.0.4+11 TEST_REUSE_JAVA_VERSION=9.0.4
  - JVM_VERSION=9.0.4 TEST_FULL_VERSION=9.0.4+11

os:
  - osx
  - linux