
sudo: required
language: generic

env:
  global:
    - JVM_WRAPPER_VERSION="`date +%Y%m%d_%H%M%S`"


install:
    
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap caskroom/versions; fi
      
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
      
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew reinstall shellcheck bats-core; fi
      
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask uninstall java; fi
      
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew search java; fi
      
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker --version; fi
      
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:duggan/bats; fi
      
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
      
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y shellcheck bats; fi
      
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-cache search oracle-; fi
      
before_script:
  - while IFS='' read -r line || [[ -n "${line}" ]]; do eval "export ${line}"; done < "samples.properties/${ENV_TEST_FILE}.env"
  - env
  - bats -v
  - shellcheck -V

jobs:
  include:

    - stage: test
      os: osx
      env:
        - ENV_TEST_FILE="openjdk-13"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: osx
      env:
        - ENV_TEST_FILE="openjdk-12"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: osx
      env:
        - ENV_TEST_FILE="openjdk-11"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: osx
      env:
        - ENV_TEST_FILE="openjdk-8"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: osx
      env:
        - ENV_TEST_FILE="oracle-11"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: osx
      env:
        - ENV_TEST_FILE="oracle-8"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      env:
        - ENV_TEST_FILE="openjdk-13"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      env:
        - ENV_TEST_FILE="openjdk-12"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      env:
        - ENV_TEST_FILE="openjdk-11"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      env:
        - ENV_TEST_FILE="openjdk-8"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      env:
        - ENV_TEST_FILE="oracle-11"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      env:
        - ENV_TEST_FILE="oracle-8"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-13"
        - DOCKER_IMAGE="centos:centos6"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-12"
        - DOCKER_IMAGE="centos:centos6"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-11"
        - DOCKER_IMAGE="centos:centos6"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-8"
        - DOCKER_IMAGE="centos:centos6"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="oracle-11"
        - DOCKER_IMAGE="centos:centos6"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="oracle-8"
        - DOCKER_IMAGE="centos:centos6"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-13"
        - DOCKER_IMAGE="centos:centos7"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-12"
        - DOCKER_IMAGE="centos:centos7"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-11"
        - DOCKER_IMAGE="centos:centos7"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-8"
        - DOCKER_IMAGE="centos:centos7"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="oracle-11"
        - DOCKER_IMAGE="centos:centos7"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="oracle-8"
        - DOCKER_IMAGE="centos:centos7"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-13"
        - DOCKER_IMAGE="debian:wheezy"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-12"
        - DOCKER_IMAGE="debian:wheezy"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-11"
        - DOCKER_IMAGE="debian:wheezy"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-8"
        - DOCKER_IMAGE="debian:wheezy"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="oracle-11"
        - DOCKER_IMAGE="debian:wheezy"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="oracle-8"
        - DOCKER_IMAGE="debian:wheezy"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-13"
        - DOCKER_IMAGE="debian:jessie"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-12"
        - DOCKER_IMAGE="debian:jessie"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-11"
        - DOCKER_IMAGE="debian:jessie"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-8"
        - DOCKER_IMAGE="debian:jessie"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="oracle-11"
        - DOCKER_IMAGE="debian:jessie"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="oracle-8"
        - DOCKER_IMAGE="debian:jessie"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-13"
        - DOCKER_IMAGE="ubuntu:trusty"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-12"
        - DOCKER_IMAGE="ubuntu:trusty"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-11"
        - DOCKER_IMAGE="ubuntu:trusty"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-8"
        - DOCKER_IMAGE="ubuntu:trusty"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="oracle-11"
        - DOCKER_IMAGE="ubuntu:trusty"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="oracle-8"
        - DOCKER_IMAGE="ubuntu:trusty"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-13"
        - DOCKER_IMAGE="opensuse:latest"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-12"
        - DOCKER_IMAGE="opensuse:latest"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-11"
        - DOCKER_IMAGE="opensuse:latest"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-8"
        - DOCKER_IMAGE="opensuse:latest"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="oracle-11"
        - DOCKER_IMAGE="opensuse:latest"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="oracle-8"
        - DOCKER_IMAGE="opensuse:latest"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-13"
        - DOCKER_IMAGE="base/archlinux:latest"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-12"
        - DOCKER_IMAGE="base/archlinux:latest"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-11"
        - DOCKER_IMAGE="base/archlinux:latest"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="openjdk-8"
        - DOCKER_IMAGE="base/archlinux:latest"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="oracle-11"
        - DOCKER_IMAGE="base/archlinux:latest"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        
    - stage: test
      os: linux
      services:
        - docker
      env:
        - ENV_TEST_FILE="oracle-8"
        - DOCKER_IMAGE="base/archlinux:latest"
      script:
        - cd ./wrapper-sh/
        - ./src/test/bash/test_docker_suite.sh
        - cd $TRAVIS_BUILD_DIR
        