sudo: required
language: generic

services:
  - docker

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap caskroom/versions; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew reinstall shellcheck bats-core; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew reinstall shellcheck bats-core; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask uninstall java; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew search java; fi
#
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker --version; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:duggan/bats; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y shellcheck bats; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y shellcheck; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-cache search oracle-; fi
#
  - git clone https://github.com/bats-core/bats-core.git && cd bats-core ./install.sh /usr/local && cd .. && rm -Rf ./bats-core/

script:
  - env
  - shellcheck src/main/bash/builder.bash || travis_terminate 1
  - src/main/bash/builder.bash || travis_terminate 1
  - where bats && bats -v
  - bats -p ./src/test/bash/jvmw.bats || bats -p ./src/test/bash/jvmw/*.bats || travis_terminate 1
  - cp ./build/jvmw ./ && ./jvmw java -fullversion || travis_terminate 1

os:
  - osx
  - linux

env:
  global:
    - DOCKER_IMAGES="centos:centos6 centos:centos7 debian:wheezy debian:jessie ubuntu:trusty opensuse:latest base/arch:latest"
  matrix:
    - ENV_TEST_FILE="openjdk-12_jdk"
    - ENV_TEST_FILE="openjdk-11_jdk"
    - ENV_TEST_FILE="openjdk-10_jdk"
    - ENV_TEST_FILE="openjdk-8_jdk"
    - ENV_TEST_FILE="oracle-11_jdk"
    - ENV_TEST_FILE="oracle-10_jdk"
    - ENV_TEST_FILE="oracle-9_jdk"
    - ENV_TEST_FILE="oracle-9.0.1_jdk"
    - ENV_TEST_FILE="oracle-8_jdk"
    - ENV_TEST_FILE="oracle-8u171_jdk"
    - ENV_TEST_FILE="oracle-1.8.0_171_jdk"
    - ENV_TEST_FILE="oracle-1.8.0_171-b11_jdk"
    - ENV_TEST_FILE="oracle-8u144_jdk"

jobs:
  include:
    - stage: deploy
      env:
        - DOCKER_IMAGES=""   ENV_TEST_FILE="oracle-"
        - COMMIT_MESSAGE="Release `date +%Y%m%d_%H%M%S`"
      script:
      - ./src/main/bash/builder.bash && cp ./build/jvmw ./ || travis_terminate 1
#      - git config --local user.name "Victor Alenkov"
#      - git config --local user.email "Victor@Alenkov.name"
#      - git commit -a -m "$COMMIT_MESSAGE" && git tag "$COMMIT_MESSAGE" && git push --tags || travis_terminate 1
