sudo: required
language: generic

services:
  - docker

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap caskroom/versions; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew reinstall shellcheck bats; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask uninstall java; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask search java; fi
#
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker --version; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:duggan/bats; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y shellcheck bats; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-cache search oracle-; fi

script:
  - env
  - bats -t ./src/test/bash/jvmw/*.bats
  - src/main/bash/builder.bash
  - shellcheck src/main/bash/builder.bash

os:
  - osx
  - linux

env:
  global:
    - DOCKER_IMAGES="centos:centos6 centos:centos7 debian:wheezy debian:jessie ubuntu:trusty opensuse:latest base/arch:latest"
  matrix:
#
    - ENV_TEST_FILE="oracle-10_jdk"
    - ENV_TEST_FILE="oracle-9_jdk"
    - ENV_TEST_FILE="oracle-9.0.1_jdk"
    - ENV_TEST_FILE="oracle-8_jdk"
    - ENV_TEST_FILE="oracle-8u171_jdk"
    - ENV_TEST_FILE="oracle-1.8.0_171_jdk"
    - ENV_TEST_FILE="oracle-1.8.0_171-b11_jdk"
    - ENV_TEST_FILE="oracle-8u144_jdk"

jobs:
  include:
    - stage: deploy
      script:
        - echo Deploy
        - ./src/main/bash/builder.bash
        - cp ./build/jvmw ./
        - git commmit
      env:
        - DOCKER_IMAGES=""   ENV_TEST_FILE="oracle-"
