sudo: false

before_install:
  - make clean
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew update ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry brew install shellcheck ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_retry python2 -m pip install pycodestyle ; fi
  - python --version

script:
  - make check

matrix:
  include:
    - os: osx
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode6.4
