sudo: required
language: generic

services:
  - docker

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew reinstall shellcheck; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap caskroom/versions; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask uninstall java; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask search java; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "x$TEST_USE_SYSTEM" == "x8" ]]; then brew cask install java8; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "x$TEST_USE_SYSTEM" == "x9" ]]; then brew cask install java9; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "x$TEST_USE_SYSTEM" == "x10" ]]; then brew cask install java; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "x$TEST_USE_SYSTEM" != "x" ]]; then /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java_home; fi
#
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker --version; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y shellcheck; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-cache search oracle-; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "x$TEST_USE_SYSTEM" == "x8" ]]; then sudo apt-get install -y oracle-java8-installer oracle-java8-set-default; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "x$TEST_USE_SYSTEM" == "x9" ]]; then sudo apt-get install -y oracle-java9-installer oracle-java9-set-default; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "x$TEST_USE_SYSTEM" == "x10" ]]; then sudo apt-get install -y oracle-java10-installer oracle-java10-set-default; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then for DOCKER_IMAGE in ${DOCKER_IMAGES}; do docker pull "${DOCKER_IMAGE}"; done; fi

before_script:
  - find . \( -name 'jdkw' -o -name '*.sh' \) -exec shellcheck -e SC1090 -x {} \;

script:
  - env
  - if [[ "x$DOCKER_IMAGES" == "x" ]]; then cd $TRAVIS_BUILD_DIR && ./src/test/bash/_test_suite.sh; fi
  - if [[ "x$DOCKER_IMAGES" != "x" ]]; then cd $TRAVIS_BUILD_DIR && ./src/test/bash/_test_docker_suite.sh; fi
#  - cd $TRAVIS_BUILD_DIR && ./jdkw info
#  - env && ./src/test/bash/_test_suite.sh && cd $TRAVIS_BUILD_DIR && ./jdkw info && JVMW_DEBUG=Y ./jdkw ./gradlew test && cd $TRAVIS_BUILD_DIR && if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then $PWD/src/test/bash/_test_docker_suite.sh; fi


os:
  - osx
  - linux

env:
  matrix:
#
    - DOCKER_IMAGES=""   ENV_TEST_FILE="10_00"
    - DOCKER_IMAGES=""   ENV_TEST_FILE="9_00"
    - DOCKER_IMAGES=""   ENV_TEST_FILE="9.0.4_00"
    - DOCKER_IMAGES=""   ENV_TEST_FILE="9.0.1_00"
    - DOCKER_IMAGES=""   ENV_TEST_FILE="8_00"
    - DOCKER_IMAGES=""   ENV_TEST_FILE="8u172_00"
    - DOCKER_IMAGES=""   ENV_TEST_FILE="8u171_00"
    - DOCKER_IMAGES=""   ENV_TEST_FILE="8u144_00"
#
    - DOCKER_IMAGES="centos:centos6"   ENV_TEST_FILE="10_00"
    - DOCKER_IMAGES="centos:centos6"   ENV_TEST_FILE="9_00"
    - DOCKER_IMAGES="centos:centos6"   ENV_TEST_FILE="9.0.4_00"
    - DOCKER_IMAGES="centos:centos6"   ENV_TEST_FILE="9.0.1_00"
    - DOCKER_IMAGES="centos:centos6"   ENV_TEST_FILE="8_00"
    - DOCKER_IMAGES="centos:centos6"   ENV_TEST_FILE="8u172_00"
    - DOCKER_IMAGES="centos:centos6"   ENV_TEST_FILE="8u171_00"
    - DOCKER_IMAGES="centos:centos6"   ENV_TEST_FILE="8u144_00"
#
    - DOCKER_IMAGES="centos:centos7"   ENV_TEST_FILE="10_00"
    - DOCKER_IMAGES="centos:centos7"   ENV_TEST_FILE="9_00"
    - DOCKER_IMAGES="centos:centos7"   ENV_TEST_FILE="9.0.4_00"
    - DOCKER_IMAGES="centos:centos7"   ENV_TEST_FILE="9.0.1_00"
    - DOCKER_IMAGES="centos:centos7"   ENV_TEST_FILE="8_00"
    - DOCKER_IMAGES="centos:centos7"   ENV_TEST_FILE="8u172_00"
    - DOCKER_IMAGES="centos:centos7"   ENV_TEST_FILE="8u171_00"
    - DOCKER_IMAGES="centos:centos7"   ENV_TEST_FILE="8u144_00"
#
    - DOCKER_IMAGES="debian:wheezy"   ENV_TEST_FILE="10_00"
    - DOCKER_IMAGES="debian:wheezy"   ENV_TEST_FILE="9_00"
    - DOCKER_IMAGES="debian:wheezy"   ENV_TEST_FILE="9.0.4_00"
    - DOCKER_IMAGES="debian:wheezy"   ENV_TEST_FILE="9.0.1_00"
    - DOCKER_IMAGES="debian:wheezy"   ENV_TEST_FILE="8_00"
    - DOCKER_IMAGES="debian:wheezy"   ENV_TEST_FILE="8u172_00"
    - DOCKER_IMAGES="debian:wheezy"   ENV_TEST_FILE="8u171_00"
    - DOCKER_IMAGES="debian:wheezy"   ENV_TEST_FILE="8u144_00"
#
    - DOCKER_IMAGES="debian:jessie"   ENV_TEST_FILE="10_00"
    - DOCKER_IMAGES="debian:jessie"   ENV_TEST_FILE="9_00"
    - DOCKER_IMAGES="debian:jessie"   ENV_TEST_FILE="9.0.4_00"
    - DOCKER_IMAGES="debian:jessie"   ENV_TEST_FILE="9.0.1_00"
    - DOCKER_IMAGES="debian:jessie"   ENV_TEST_FILE="8_00"
    - DOCKER_IMAGES="debian:jessie"   ENV_TEST_FILE="8u172_00"
    - DOCKER_IMAGES="debian:jessie"   ENV_TEST_FILE="8u171_00"
    - DOCKER_IMAGES="debian:jessie"   ENV_TEST_FILE="8u144_00"
#
    - DOCKER_IMAGES="ubuntu:trusty"   ENV_TEST_FILE="10_00"
    - DOCKER_IMAGES="ubuntu:trusty"   ENV_TEST_FILE="9_00"
    - DOCKER_IMAGES="ubuntu:trusty"   ENV_TEST_FILE="9.0.4_00"
    - DOCKER_IMAGES="ubuntu:trusty"   ENV_TEST_FILE="9.0.1_00"
    - DOCKER_IMAGES="ubuntu:trusty"   ENV_TEST_FILE="8_00"
    - DOCKER_IMAGES="ubuntu:trusty"   ENV_TEST_FILE="8u172_00"
    - DOCKER_IMAGES="ubuntu:trusty"   ENV_TEST_FILE="8u171_00"
    - DOCKER_IMAGES="ubuntu:trusty"   ENV_TEST_FILE="8u144_00"
#
    - DOCKER_IMAGES="opensuse:latest"   ENV_TEST_FILE="10_00"
    - DOCKER_IMAGES="opensuse:latest"   ENV_TEST_FILE="9_00"
    - DOCKER_IMAGES="opensuse:latest"   ENV_TEST_FILE="9.0.4_00"
    - DOCKER_IMAGES="opensuse:latest"   ENV_TEST_FILE="9.0.1_00"
    - DOCKER_IMAGES="opensuse:latest"   ENV_TEST_FILE="8_00"
    - DOCKER_IMAGES="opensuse:latest"   ENV_TEST_FILE="8u172_00"
    - DOCKER_IMAGES="opensuse:latest"   ENV_TEST_FILE="8u171_00"
    - DOCKER_IMAGES="opensuse:latest"   ENV_TEST_FILE="8u144_00"
#
    - DOCKER_IMAGES="base/arch:latest"   ENV_TEST_FILE="10_00"
    - DOCKER_IMAGES="base/arch:latest"   ENV_TEST_FILE="9_00"
    - DOCKER_IMAGES="base/arch:latest"   ENV_TEST_FILE="9.0.4_00"
    - DOCKER_IMAGES="base/arch:latest"   ENV_TEST_FILE="9.0.1_00"
    - DOCKER_IMAGES="base/arch:latest"   ENV_TEST_FILE="8_00"
    - DOCKER_IMAGES="base/arch:latest"   ENV_TEST_FILE="8u172_00"
    - DOCKER_IMAGES="base/arch:latest"   ENV_TEST_FILE="8u171_00"
    - DOCKER_IMAGES="base/arch:latest"   ENV_TEST_FILE="8u144_00"

jobs:
  include:
    - stage: deploy
      script: echo Deploy
