sudo: false
language: python

install:
  - make clean
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then source ./travis_scripts/before_install.sh ; fi
  - python --version

script:
  - make check

matrix:
  include:
    - os: osx
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode6.4
