sudo: required
language: generic

services:
  - docker

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew reinstall shellcheck; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap caskroom/versions; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask uninstall java; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask search java; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "x$TEST_USE_SYSTEM" == "x7" ]]; then brew cask install java7; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "x$TEST_USE_SYSTEM" == "x8" ]]; then brew cask install java8; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "x$TEST_USE_SYSTEM" == "x9" ]]; then brew cask install java9; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "x$TEST_USE_SYSTEM" == "x10" ]]; then brew cask install java; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "x$TEST_USE_SYSTEM" != "x" ]]; then /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java_home; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker --version; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y shellcheck; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-cache search oracle-; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "x$TEST_USE_SYSTEM" == "x7" ]]; then sudo apt-get install -y oracle-java7-installer oracle-java7-set-default; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "x$TEST_USE_SYSTEM" == "x8" ]]; then sudo apt-get install -y oracle-java8-installer oracle-java8-set-default; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "x$TEST_USE_SYSTEM" == "x9" ]]; then sudo apt-get install -y oracle-java9-installer oracle-java9-set-default; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "x$TEST_USE_SYSTEM" == "x10" ]]; then sudo apt-get install -y oracle-java10-installer oracle-java10-set-default; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then for DOCKER_IMAGE in ${DOCKER_IMAGES}; do docker pull "${DOCKER_IMAGE}"; done; fi

before_script:
  - find . \( -name 'jdkw' -o -name '*.sh' \) -exec shellcheck -e SC1090 -x {} \;

script:
  - env
  - ./src/test/bash/_test_suite.sh
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./src/test/bash/_test_docker_suite.sh; fi

env:
  global:
    - DOCKER_IMAGES="centos:centos6 centos:centos7 debian:wheezy debian:jessie ubuntu:trusty opensuse:latest base/arch:latest"

matrix:
  include:
#  OSX, JVM
    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=10
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=10.0.1+10
        - TEST_USE_SYSTEM=10

    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=9
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=9.0.4+11
        - TEST_REUSE_JAVA_VERSION=9.0.4
#        - TEST_USE_SYSTEM=9

    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=9.0.4
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=9.0.4+11
#        - TEST_USE_SYSTEM=9

    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=9.0.1
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=9.0.1+11

    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=8
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.8.0_171-b11
        - TEST_REUSE_JAVA_VERSION=8u171

    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=8u171
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.8.0_171-b11

    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=8u172
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.8.0_172-b11
        - TEST_USE_SYSTEM=8

    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=8u144
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.8.0_144-b01

    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=7
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.7.0_80-b15
        - TEST_REUSE_JAVA_VERSION=7u80
#        - TEST_USE_SYSTEM=7

    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=7u80
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.7.0_80-b15

    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=7u65
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.7.0_65-b17

#
#  OSX, JDK
    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=10
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=10.0.1+10
        - TEST_USE_SYSTEM=10

    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=9
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=9.0.4+11
        - TEST_REUSE_JAVA_VERSION=9.0.4
        - TEST_USE_SYSTEM=9

    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=9.0.4
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=9.0.4+11
        - TEST_USE_SYSTEM=9

    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=9.0.1
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=9.0.1+11

    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=8
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.8.0_171-b11
        - TEST_REUSE_JAVA_VERSION=8u171

    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=8u171
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.8.0_171-b11

    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=8u172
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.8.0_172-b11
        - TEST_USE_SYSTEM=8

    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=8u144
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.8.0_144-b01

    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=7
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.7.0_80-b15
        - TEST_REUSE_JAVA_VERSION=7u80

    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=7u80
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.7.0_80-b15

    - os: osx
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=7u65
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.7.0_65-b17

#  Linux, JVM
    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=10
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=10.0.1+10
#        - TEST_USE_SYSTEM=10

    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=9
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=9.0.4+11
        - TEST_REUSE_JAVA_VERSION=9.0.4
        - TEST_USE_SYSTEM=9

    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=9.0.4
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=9.0.4+11
        - TEST_USE_SYSTEM=9

    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=9.0.1
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=9.0.1+11

    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=8
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.8.0_171-b11
        - TEST_REUSE_JAVA_VERSION=8u171
        - TEST_USE_SYSTEM=8

    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=8u171
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.8.0_171-b11
        - TEST_USE_SYSTEM=8

    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=8u172
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.8.0_172-b11

    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=8u144
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.8.0_144-b01

    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=7
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.7.0_80-b15
        - TEST_REUSE_JAVA_VERSION=7u80

    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=7u80
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.7.0_80-b15

    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=7u65
        - TEST_TYPE=jvm
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.7.0_65-b17

#
#  Linux, JDK
    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=10
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=10.0.1+10
#        - TEST_USE_SYSTEM=10

    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=9
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=9.0.4+11
        - TEST_REUSE_JAVA_VERSION=9.0.4
        - TEST_USE_SYSTEM=9

    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=9.0.4
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=9.0.4+11
        - TEST_USE_SYSTEM=9

    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=9.0.1
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=9.0.1+11

    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=8
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.8.0_171-b11
        - TEST_REUSE_JAVA_VERSION=8u171
        - TEST_USE_SYSTEM=8

    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=8u171
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.8.0_171-b11
        - TEST_USE_SYSTEM=8

    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=8u172
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.8.0_172-b11

    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=8u144
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.8.0_144-b01

    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=7
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.7.0_80-b15
        - TEST_REUSE_JAVA_VERSION=7u80

    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=7u80
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.7.0_80-b15
#        - TEST_USE_SYSTEM=7

    - os: linux
      env:
        - TEST_JVM_VENDOR=oracle
        - TEST_JVM_VERSION=7u65
        - TEST_TYPE=jdk
        - TEST_JVM_TYPE=jdk
        - TEST_FULL_VERSION=1.7.0_65-b17
