sudo: false
language: generic

services:
  - docker

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$SKIP_SHELLCHECK" != "yes" ]] ; then travis_retry brew update && travis_retry brew install shellcheck; fi
  - chmod +x ./travis_scripts/*.sh

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$SKIP_SHELLCHECK" != "yes" ]] ; then find . \( -name 'jdkw' -o -name '*.sh' \) -exec shellcheck {} \; ; fi
  - if [[ ! -z "$DOCKER_IMAGE" ]]; then sudo docker pull $DOCKER_IMAGE:$DOCKER_TAG; fi

script:
  - if [[ -z "$DOCKER_IMAGE" ]]; then ./test_suite.sh 2>&1; fi
  - if [[ ! -z "$DOCKER_IMAGE" ]]; then ./travis_scripts/script_docker.$DOCKER_IMAGE.sh 2>&1; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CHECK_JDK_VERSION='1.6.0_45' CHECK_JDK_HOME='jdk6u45' JVMW_FILE='jvmw.6u45.properties' ./tests.sh ; fi

matrix:
  include:
    - os: osx
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode6.4
      env:
        - SKIP_SHELLCHECK=yes

    - os: linux
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: precise
      sudo: required

    - os: linux
      sudo: required
      env:
        - DOCKER_IMAGE: centos
        - DOCKER_TAG: centos6
    - os: linux
      sudo: required
      env:
        - DOCKER_IMAGE: centos
        - DOCKER_TAG: centos7
      env:
        - DOCKER_IMAGE: centos
        - DOCKER_TAG: centos6
    - os: linux
      sudo: required
      env:
        - DOCKER_IMAGE: debian
        - DOCKER_TAG: wheezy
    - os: linux
      sudo: required
      env:
        - DOCKER_IMAGE: debian
        - DOCKER_TAG: jessie
    - os: linux
      sudo: required
      env:
        - DOCKER_IMAGE: ubuntu
        - DOCKER_TAG: trusty
    - os: linux
      sudo: required
      env:
        - DOCKER_IMAGE: opensuse
        - DOCKER_TAG: latest
    - os: linux
      sudo: required
      env:
        - DOCKER_IMAGE: alpine
        - DOCKER_TAG: latest
    - os: linux
      sudo: required
      env:
        - DOCKER_IMAGE: base/arch
        - DOCKER_TAG: latest
      script:
        - ./travis_scripts/script_docker.$DOCKER_IMAGE.sh 2>&1
